#!/bin/bash
echo "======================================"
echo "Docker Memory Configuration Guide"
echo "======================================"
echo ""
echo "Current Docker container stats:"
docker stats --no-stream --format "table {{.Container}}\t{{.MemUsage}}\t{{.MemPerc}}" 2>/dev/null || echo "  (Need to run from outside container)"
echo ""
echo "======================================"
echo "How to Increase Docker Memory:"
echo "======================================"
echo ""
echo "OPTION 1: Docker Desktop (Windows/Mac)"
echo "  1. Open Docker Desktop"
echo "  2. Go to Settings (gear icon)"
echo "  3. Navigate to: Resources → Memory"
echo "  4. Increase slider to at least 24 GB"
echo "  5. Click 'Apply & Restart'"
echo ""
echo "OPTION 2: Docker CLI (restart container with more memory)"
echo "  Exit this container and run:"
echo "  docker run -it --memory=\"24g\" --memory-swap=\"32g\" \\"
echo "    -v /path/to/NeuPIMs:/workspace \\"
echo "    your-image-name bash"
echo ""
echo "OPTION 3: Edit Docker daemon config (Linux)"
echo "  Edit /etc/docker/daemon.json:"
echo '  {'
echo '    "default-shm-size": "24G"'
echo '  }'
echo "  Then: sudo systemctl restart docker"
echo ""
echo "OPTION 4: docker-compose (if using)"
echo "  Add to your service in docker-compose.yml:"
echo "  mem_limit: 24g"
echo "  memswap_limit: 32g"
echo ""
echo "======================================"
echo "Recommended Settings for 16,384 tokens:"
echo "======================================"
echo "  Memory:      24 GB (minimum 20 GB)"
echo "  Memory Swap: 32 GB"
echo "  Shared Memory: 2 GB"
echo ""
echo "After increasing memory, run:"
echo "  ./brun_fast.sh"
echo ""
