#!/bin/bash
echo "=== Memory Optimization for 16,384 Tokens ==="
echo ""
echo "If you can't increase RAM, try these in order:"
echo ""
echo "1. CLOSE OTHER APPLICATIONS"
echo "   - Close browsers, IDEs, other Docker containers"
echo "   - Free up as much RAM as possible"
echo ""
echo "2. RUN WITH SWAP (on host):"
echo "   sudo fallocate -l 16G /swapfile"
echo "   sudo chmod 600 /swapfile"  
echo "   sudo mkswap /swapfile"
echo "   sudo swapon /swapfile"
echo ""
echo "3. LIMIT PARALLELISM (edit configs):"
echo "   - Edit systolic_ws_128x128_dev.json"
echo "   - Set 'num_cores': 1 (already set)"
echo ""
echo "4. USE SMALLER BATCH (fallback):"
echo "   - Use 8192 tokens instead (needs ~8GB)"
echo "   - Run twice to process full dataset"
echo ""
