#!/bin/bash
echo "======================================"
echo "Swap Space - One-Time Setup Guide"
echo "======================================"
echo ""
echo "✅ DO ONCE (on host machine):"
echo "────────────────────────────────────"
echo "1. Create swap file:"
echo "   sudo fallocate -l 16G /swapfile"
echo "   sudo chmod 600 /swapfile"
echo "   sudo mkswap /swapfile"
echo "   sudo swapon /swapfile"
echo ""
echo "2. Make it PERMANENT (survives reboots):"
echo "   echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab"
echo ""
echo "✅ DONE! Never need to do again."
echo ""
echo "────────────────────────────────────"
echo "After that, every time you run:"
echo "────────────────────────────────────"
echo "1. Start Docker container (if stopped)"
echo "2. cd /home/akash/NeuPIMs"
echo "3. ./brun_fast.sh"
echo ""
echo "The swap space is ALWAYS available!"
echo ""
echo "────────────────────────────────────"
echo "To check if swap is active:"
echo "────────────────────────────────────"
echo "Run: free -h"
echo ""
echo "You should see something like:"
echo "              total    used    free"
echo "Mem:           15Gi    2Gi    13Gi"
echo "Swap:          16Gi    0Gi    16Gi  ← Swap active!"
echo ""
